import { index, integer, primaryKey, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = { createdAt: integer("created_at", { mode: "timestamp" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(), deletedAt: integer("deleted_at", { mode: "timestamp" }) };

export const roles = sqliteTable("roles", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull().unique(), description: text("description"), ...timestamps });
export const permissions = sqliteTable("permissions", { id: integer("id").primaryKey({ autoIncrement: true }), key: text("key").notNull().unique(), description: text("description"), ...timestamps });
export const rolePermissions = sqliteTable("role_permissions", { roleId: integer("role_id").notNull().references(()=>roles.id), permissionId: integer("permission_id").notNull().references(()=>permissions.id) }, t=>[primaryKey({columns:[t.roleId,t.permissionId]})]);
export const users = sqliteTable("users", { id: text("id").primaryKey(), roleId: integer("role_id").notNull().references(()=>roles.id), name: text("name").notNull(), email: text("email").notNull(), phone: text("phone").notNull(), passwordHash: text("password_hash").notNull(), status: text("status", { enum:["active","inactive","locked","pending"] }).notNull().default("pending"), verifiedAt: integer("verified_at",{mode:"timestamp"}), failedAttempts: integer("failed_attempts").notNull().default(0), ...timestamps }, t=>[uniqueIndex("users_email_uq").on(t.email),uniqueIndex("users_phone_uq").on(t.phone),index("users_role_idx").on(t.roleId)]);
export const customers = sqliteTable("customers", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(()=>users.id), notificationPreferences: text("notification_preferences",{mode:"json"}), loyaltyVisits: integer("loyalty_visits").notNull().default(0), ...timestamps },t=>[uniqueIndex("customers_user_uq").on(t.userId)]);
export const employees = sqliteTable("employees", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(()=>users.id), employeeCode: text("employee_code").notNull(), specialty: text("specialty"), status: text("status").notNull().default("active"), ...timestamps },t=>[uniqueIndex("employees_user_uq").on(t.userId),uniqueIndex("employees_code_uq").on(t.employeeCode)]);
export const vehicles = sqliteTable("vehicles", { id: text("id").primaryKey(), customerId: text("customer_id").notNull().references(()=>customers.id), plate: text("plate").notNull(), brand: text("brand").notNull(), model: text("model").notNull(), year: integer("year"), color: text("color"), type: text("type",{enum:["sedan","suv","pickup","microbus","motorcycle","other"]}).notNull(), imageUrl: text("image_url"), notes: text("notes"), isPrimary: integer("is_primary",{mode:"boolean"}).notNull().default(false), isActive: integer("is_active",{mode:"boolean"}).notNull().default(true), ...timestamps },t=>[uniqueIndex("vehicles_plate_uq").on(t.plate),index("vehicles_customer_idx").on(t.customerId)]);
export const services = sqliteTable("services", { id: text("id").primaryKey(), name: text("name").notNull(), slug: text("slug").notNull(), description: text("description").notNull(), imageUrl: text("image_url"), basePrice: real("base_price").notNull(), estimatedMinutes: integer("estimated_minutes").notNull(), vehicleTypes: text("vehicle_types",{mode:"json"}), isActive: integer("is_active",{mode:"boolean"}).notNull().default(true), displayOrder: integer("display_order").notNull().default(0), ...timestamps },t=>[uniqueIndex("services_slug_uq").on(t.slug),index("services_active_order_idx").on(t.isActive,t.displayOrder)]);
export const serviceStages = sqliteTable("service_stages", { id: text("id").primaryKey(), serviceId: text("service_id").references(()=>services.id), key: text("key").notNull(), name: text("name").notNull(), displayOrder: integer("display_order").notNull(), weight: integer("weight").notNull().default(1), isSpecial: integer("is_special",{mode:"boolean"}).notNull().default(false), isActive: integer("is_active",{mode:"boolean"}).notNull().default(true), ...timestamps },t=>[index("stages_service_order_idx").on(t.serviceId,t.displayOrder)]);
export const serviceOrders = sqliteTable("service_orders", { id: text("id").primaryKey(), code: text("code").notNull(), customerId: text("customer_id").notNull().references(()=>customers.id), vehicleId: text("vehicle_id").notNull().references(()=>vehicles.id), currentStageId: text("current_stage_id").references(()=>serviceStages.id), status: text("status",{enum:["received","queued","in_progress","paused","authorization_required","delayed","ready","delivered","cancelled"]}).notNull(), receivedAt: integer("received_at",{mode:"timestamp"}).notNull(), estimatedAt: integer("estimated_at",{mode:"timestamp"}), completedAt: integer("completed_at",{mode:"timestamp"}), deliveredAt: integer("delivered_at",{mode:"timestamp"}), progress: integer("progress").notNull().default(0), total: real("total").notNull(), paymentStatus: text("payment_status").notNull().default("pending"), pickupCodeHash: text("pickup_code_hash"), clientNotes: text("client_notes"), version: integer("version").notNull().default(1), ...timestamps },t=>[uniqueIndex("orders_code_uq").on(t.code),index("orders_customer_idx").on(t.customerId),index("orders_vehicle_idx").on(t.vehicleId),index("orders_status_received_idx").on(t.status,t.receivedAt)]);
export const orderItems = sqliteTable("order_items", { id: text("id").primaryKey(), orderId: text("order_id").notNull().references(()=>serviceOrders.id), serviceId: text("service_id").notNull().references(()=>services.id), quantity: integer("quantity").notNull().default(1), unitPrice: real("unit_price").notNull(), discount: real("discount").notNull().default(0), subtotal: real("subtotal").notNull(), ...timestamps },t=>[index("order_items_order_idx").on(t.orderId)]);
export const orderStatusHistory = sqliteTable("order_status_history", { id: text("id").primaryKey(), orderId: text("order_id").notNull().references(()=>serviceOrders.id), previousStageId: text("previous_stage_id").references(()=>serviceStages.id), newStageId: text("new_stage_id").references(()=>serviceStages.id), changedByUserId: text("changed_by_user_id").notNull().references(()=>users.id), internalComment: text("internal_comment"), clientComment: text("client_comment"), evidenceUrl: text("evidence_url"), estimatedAt: integer("estimated_at",{mode:"timestamp"}), createdAt: integer("created_at",{mode:"timestamp"}).notNull() },t=>[index("history_order_created_idx").on(t.orderId,t.createdAt)]);
export const employeeAssignments = sqliteTable("employee_assignments", { id: text("id").primaryKey(), orderId: text("order_id").notNull().references(()=>serviceOrders.id), employeeId: text("employee_id").notNull().references(()=>employees.id), assignedByUserId: text("assigned_by_user_id").notNull().references(()=>users.id), assignedAt: integer("assigned_at",{mode:"timestamp"}).notNull(), endedAt: integer("ended_at",{mode:"timestamp"}) },t=>[index("assignments_order_idx").on(t.orderId),index("assignments_employee_idx").on(t.employeeId)]);
export const promotions = sqliteTable("promotions", { id: text("id").primaryKey(), name: text("name").notNull(), description: text("description").notNull(), code: text("code"), discountType: text("discount_type",{enum:["percentage","fixed"]}).notNull(), discountValue: real("discount_value").notNull(), status: text("status",{enum:["draft","scheduled","active","finished","inactive"]}).notNull(), startsAt: integer("starts_at",{mode:"timestamp"}), endsAt: integer("ends_at",{mode:"timestamp"}), usageLimit: integer("usage_limit"), perCustomerLimit: integer("per_customer_limit"), conditions: text("conditions",{mode:"json"}), ...timestamps },t=>[uniqueIndex("promotions_code_uq").on(t.code),index("promotions_status_dates_idx").on(t.status,t.startsAt,t.endsAt)]);
export const promotionServices = sqliteTable("promotion_services", { promotionId: text("promotion_id").notNull().references(()=>promotions.id), serviceId: text("service_id").notNull().references(()=>services.id) },t=>[primaryKey({columns:[t.promotionId,t.serviceId]})]);
export const promotionRedemptions = sqliteTable("promotion_redemptions", { id: text("id").primaryKey(), promotionId: text("promotion_id").notNull().references(()=>promotions.id), orderId: text("order_id").notNull().references(()=>serviceOrders.id), customerId: text("customer_id").notNull().references(()=>customers.id), amount: real("amount").notNull(), redeemedAt: integer("redeemed_at",{mode:"timestamp"}).notNull() },t=>[uniqueIndex("redemptions_order_promo_uq").on(t.orderId,t.promotionId),index("redemptions_customer_idx").on(t.customerId)]);
export const notifications = sqliteTable("notifications", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(()=>users.id), orderId: text("order_id").references(()=>serviceOrders.id), type: text("type").notNull(), title: text("title").notNull(), message: text("message").notNull(), readAt: integer("read_at",{mode:"timestamp"}), createdAt: integer("created_at",{mode:"timestamp"}).notNull() },t=>[index("notifications_user_read_idx").on(t.userId,t.readAt)]);
export const notificationLogs = sqliteTable("notification_logs", { id: text("id").primaryKey(), notificationId: text("notification_id").notNull().references(()=>notifications.id), channel: text("channel",{enum:["in_app","email","sms","whatsapp","push"]}).notNull(), status: text("status",{enum:["queued","sent","failed","retrying"]}).notNull(), attempt: integer("attempt").notNull().default(1), providerReference: text("provider_reference"), error: text("error"), attemptedAt: integer("attempted_at",{mode:"timestamp"}).notNull() },t=>[index("notification_logs_status_idx").on(t.status,t.attemptedAt)]);
export const payments = sqliteTable("payments", { id: text("id").primaryKey(), orderId: text("order_id").notNull().references(()=>serviceOrders.id), method: text("method").notNull(), amount: real("amount").notNull(), status: text("status").notNull(), reference: text("reference"), paidAt: integer("paid_at",{mode:"timestamp"}), ...timestamps },t=>[index("payments_order_idx").on(t.orderId)]);
export const contactMessages = sqliteTable("contact_messages", { id: text("id").primaryKey(), name: text("name").notNull(), contact: text("contact").notNull(), message: text("message").notNull(), status: text("status").notNull().default("new"), createdAt: integer("created_at",{mode:"timestamp"}).notNull() });
export const reviews = sqliteTable("reviews", { id: text("id").primaryKey(), orderId: text("order_id").notNull().references(()=>serviceOrders.id), customerId: text("customer_id").notNull().references(()=>customers.id), rating: integer("rating").notNull(), comment: text("comment"), isPublished: integer("is_published",{mode:"boolean"}).notNull().default(false), ...timestamps },t=>[uniqueIndex("reviews_order_uq").on(t.orderId)]);
export const businessSettings = sqliteTable("business_settings", { key: text("key").primaryKey(), value: text("value",{mode:"json"}).notNull(), isPublic: integer("is_public",{mode:"boolean"}).notNull().default(false), updatedByUserId: text("updated_by_user_id").references(()=>users.id), updatedAt: integer("updated_at",{mode:"timestamp"}).notNull() });
export const auditLogs = sqliteTable("audit_logs", { id: text("id").primaryKey(), actorUserId: text("actor_user_id").references(()=>users.id), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id"), before: text("before",{mode:"json"}), after: text("after",{mode:"json"}), ipHash: text("ip_hash"), userAgent: text("user_agent"), createdAt: integer("created_at",{mode:"timestamp"}).notNull() },t=>[index("audit_entity_idx").on(t.entityType,t.entityId),index("audit_actor_created_idx").on(t.actorUserId,t.createdAt)]);
